### ISSUE TITLE
Roles for the SONATA SP microservices

### ISSUE THREAD

**Issue by tsoenen** [sonata-nfv/son-gkeeper#817] opened 2017-08-11 13:35 UTC
When trying to register the SLM as a microservice with the GK, I noticed that only a limited set of `clientId`'s where allowed to register with. None of these available `clientId`'s fit with the SLM, so for now, I have been using the `clientId` of `son-monitor`: https://github.com/sonata-nfv/son-mano-framework/blob/master/plugins/son-mano-service-lifecycle-management/son_mano_slm/slm.py#L98

Is it possible to add an additional role: `son-servicelifecyclemanager` ?

**Comment by dang03** [comment] 2017-08-25 09:10
Hi @tsoenen, sorry for the late response, today I'm back from holidays.
You are right, the GK limits the micro-service registration to allow only components that belong to the Service Platform. It initially uses predefined roles using the `clientId` name.

The SLM is already allowed, but it was simply named `slm`. I will update the role name to a more proper `son-slm` so you can register a micro-service with `clientId` `son-slm`

**Comment by jbonnet** [comment] 2017-09-13 16:50
Hey, @tsoenen and @dang03 
Is this issue fixed?

**Comment by dang03** [comment] 2017-09-14 07:47
Hi @jbonnet,
I've seen `son-monitor` being registered as micro-service in the User Management these days. `son-slm` should have no problems to register too. I guess the issue is solved but @tsoenen should confirm this.

**Comment by jbonnet** [comment] 2017-09-14 12:41
Ok, so I'm closing it...

**Closed by jbonnet** 2017-09-14 12:41 UTC
